/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppReceivablesRouteImport } from './routes/_app.receivables'
import { Route as AppProductsRouteImport } from './routes/_app.products'
import { Route as AppPayablesRouteImport } from './routes/_app.payables'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppExpensesRouteImport } from './routes/_app.expenses'
import { Route as AppContactsRouteImport } from './routes/_app.contacts'
import { Route as AppSettingsIndexRouteImport } from './routes/_app.settings.index'
import { Route as AppInventoryIndexRouteImport } from './routes/_app.inventory.index'
import { Route as AppStatementsVendorRouteImport } from './routes/_app.statements.vendor'
import { Route as AppStatementsCustomerRouteImport } from './routes/_app.statements.customer'
import { Route as AppSettlementVendorRouteImport } from './routes/_app.settlement.vendor'
import { Route as AppSettlementCustomerRouteImport } from './routes/_app.settlement.customer'
import { Route as AppSettingsUsersRouteImport } from './routes/_app.settings.users'
import { Route as AppSettingsPermissionsRouteImport } from './routes/_app.settings.permissions'
import { Route as AppSettingsOpeningRouteImport } from './routes/_app.settings.opening'
import { Route as AppReportsSalespersonRouteImport } from './routes/_app.reports.salesperson'
import { Route as AppReportsSalesDetailRouteImport } from './routes/_app.reports.sales-detail'
import { Route as AppReportsRevenueRouteImport } from './routes/_app.reports.revenue'
import { Route as AppReportsPurchaseDetailRouteImport } from './routes/_app.reports.purchase-detail'
import { Route as AppReportsProductProfitRouteImport } from './routes/_app.reports.product-profit'
import { Route as AppReportsPnlRouteImport } from './routes/_app.reports.pnl'
import { Route as AppReportsCustomerProfitRouteImport } from './routes/_app.reports.customer-profit'
import { Route as AppReportsAgingRouteImport } from './routes/_app.reports.aging'
import { Route as AppInventoryLedgerRouteImport } from './routes/_app.inventory.ledger'
import { Route as AppDocsSalesReturnRouteImport } from './routes/_app.docs.sales-return'
import { Route as AppDocsSalesOrderRouteImport } from './routes/_app.docs.sales-order'
import { Route as AppDocsSalesInvoiceRouteImport } from './routes/_app.docs.sales-invoice'
import { Route as AppDocsQuotationRouteImport } from './routes/_app.docs.quotation'
import { Route as AppDocsPurchaseReceiptRouteImport } from './routes/_app.docs.purchase-receipt'
import { Route as AppDocsPurchaseOrderRouteImport } from './routes/_app.docs.purchase-order'
import { Route as AppDocsInventoryAdjustRouteImport } from './routes/_app.docs.inventory-adjust'
import { Route as AppPrintDocTypeIdRouteImport } from './routes/_app.print.$docType.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReceivablesRoute = AppReceivablesRouteImport.update({
  id: '/receivables',
  path: '/receivables',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppPayablesRoute = AppPayablesRouteImport.update({
  id: '/payables',
  path: '/payables',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsRoute = AppContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppInventoryIndexRoute = AppInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => AppRoute,
} as any)
const AppStatementsVendorRoute = AppStatementsVendorRouteImport.update({
  id: '/statements/vendor',
  path: '/statements/vendor',
  getParentRoute: () => AppRoute,
} as any)
const AppStatementsCustomerRoute = AppStatementsCustomerRouteImport.update({
  id: '/statements/customer',
  path: '/statements/customer',
  getParentRoute: () => AppRoute,
} as any)
const AppSettlementVendorRoute = AppSettlementVendorRouteImport.update({
  id: '/settlement/vendor',
  path: '/settlement/vendor',
  getParentRoute: () => AppRoute,
} as any)
const AppSettlementCustomerRoute = AppSettlementCustomerRouteImport.update({
  id: '/settlement/customer',
  path: '/settlement/customer',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsUsersRoute = AppSettingsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsPermissionsRoute = AppSettingsPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsOpeningRoute = AppSettingsOpeningRouteImport.update({
  id: '/opening',
  path: '/opening',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppReportsSalespersonRoute = AppReportsSalespersonRouteImport.update({
  id: '/reports/salesperson',
  path: '/reports/salesperson',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsSalesDetailRoute = AppReportsSalesDetailRouteImport.update({
  id: '/reports/sales-detail',
  path: '/reports/sales-detail',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRevenueRoute = AppReportsRevenueRouteImport.update({
  id: '/reports/revenue',
  path: '/reports/revenue',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsPurchaseDetailRoute =
  AppReportsPurchaseDetailRouteImport.update({
    id: '/reports/purchase-detail',
    path: '/reports/purchase-detail',
    getParentRoute: () => AppRoute,
  } as any)
const AppReportsProductProfitRoute = AppReportsProductProfitRouteImport.update({
  id: '/reports/product-profit',
  path: '/reports/product-profit',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsPnlRoute = AppReportsPnlRouteImport.update({
  id: '/reports/pnl',
  path: '/reports/pnl',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsCustomerProfitRoute =
  AppReportsCustomerProfitRouteImport.update({
    id: '/reports/customer-profit',
    path: '/reports/customer-profit',
    getParentRoute: () => AppRoute,
  } as any)
const AppReportsAgingRoute = AppReportsAgingRouteImport.update({
  id: '/reports/aging',
  path: '/reports/aging',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryLedgerRoute = AppInventoryLedgerRouteImport.update({
  id: '/inventory/ledger',
  path: '/inventory/ledger',
  getParentRoute: () => AppRoute,
} as any)
const AppDocsSalesReturnRoute = AppDocsSalesReturnRouteImport.update({
  id: '/docs/sales-return',
  path: '/docs/sales-return',
  getParentRoute: () => AppRoute,
} as any)
const AppDocsSalesOrderRoute = AppDocsSalesOrderRouteImport.update({
  id: '/docs/sales-order',
  path: '/docs/sales-order',
  getParentRoute: () => AppRoute,
} as any)
const AppDocsSalesInvoiceRoute = AppDocsSalesInvoiceRouteImport.update({
  id: '/docs/sales-invoice',
  path: '/docs/sales-invoice',
  getParentRoute: () => AppRoute,
} as any)
const AppDocsQuotationRoute = AppDocsQuotationRouteImport.update({
  id: '/docs/quotation',
  path: '/docs/quotation',
  getParentRoute: () => AppRoute,
} as any)
const AppDocsPurchaseReceiptRoute = AppDocsPurchaseReceiptRouteImport.update({
  id: '/docs/purchase-receipt',
  path: '/docs/purchase-receipt',
  getParentRoute: () => AppRoute,
} as any)
const AppDocsPurchaseOrderRoute = AppDocsPurchaseOrderRouteImport.update({
  id: '/docs/purchase-order',
  path: '/docs/purchase-order',
  getParentRoute: () => AppRoute,
} as any)
const AppDocsInventoryAdjustRoute = AppDocsInventoryAdjustRouteImport.update({
  id: '/docs/inventory-adjust',
  path: '/docs/inventory-adjust',
  getParentRoute: () => AppRoute,
} as any)
const AppPrintDocTypeIdRoute = AppPrintDocTypeIdRouteImport.update({
  id: '/print/$docType/$id',
  path: '/print/$docType/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/contacts': typeof AppContactsRoute
  '/expenses': typeof AppExpensesRoute
  '/notifications': typeof AppNotificationsRoute
  '/payables': typeof AppPayablesRoute
  '/products': typeof AppProductsRoute
  '/receivables': typeof AppReceivablesRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/docs/inventory-adjust': typeof AppDocsInventoryAdjustRoute
  '/docs/purchase-order': typeof AppDocsPurchaseOrderRoute
  '/docs/purchase-receipt': typeof AppDocsPurchaseReceiptRoute
  '/docs/quotation': typeof AppDocsQuotationRoute
  '/docs/sales-invoice': typeof AppDocsSalesInvoiceRoute
  '/docs/sales-order': typeof AppDocsSalesOrderRoute
  '/docs/sales-return': typeof AppDocsSalesReturnRoute
  '/inventory/ledger': typeof AppInventoryLedgerRoute
  '/reports/aging': typeof AppReportsAgingRoute
  '/reports/customer-profit': typeof AppReportsCustomerProfitRoute
  '/reports/pnl': typeof AppReportsPnlRoute
  '/reports/product-profit': typeof AppReportsProductProfitRoute
  '/reports/purchase-detail': typeof AppReportsPurchaseDetailRoute
  '/reports/revenue': typeof AppReportsRevenueRoute
  '/reports/sales-detail': typeof AppReportsSalesDetailRoute
  '/reports/salesperson': typeof AppReportsSalespersonRoute
  '/settings/opening': typeof AppSettingsOpeningRoute
  '/settings/permissions': typeof AppSettingsPermissionsRoute
  '/settings/users': typeof AppSettingsUsersRoute
  '/settlement/customer': typeof AppSettlementCustomerRoute
  '/settlement/vendor': typeof AppSettlementVendorRoute
  '/statements/customer': typeof AppStatementsCustomerRoute
  '/statements/vendor': typeof AppStatementsVendorRoute
  '/inventory/': typeof AppInventoryIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/print/$docType/$id': typeof AppPrintDocTypeIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/contacts': typeof AppContactsRoute
  '/expenses': typeof AppExpensesRoute
  '/notifications': typeof AppNotificationsRoute
  '/payables': typeof AppPayablesRoute
  '/products': typeof AppProductsRoute
  '/receivables': typeof AppReceivablesRoute
  '/': typeof AppIndexRoute
  '/docs/inventory-adjust': typeof AppDocsInventoryAdjustRoute
  '/docs/purchase-order': typeof AppDocsPurchaseOrderRoute
  '/docs/purchase-receipt': typeof AppDocsPurchaseReceiptRoute
  '/docs/quotation': typeof AppDocsQuotationRoute
  '/docs/sales-invoice': typeof AppDocsSalesInvoiceRoute
  '/docs/sales-order': typeof AppDocsSalesOrderRoute
  '/docs/sales-return': typeof AppDocsSalesReturnRoute
  '/inventory/ledger': typeof AppInventoryLedgerRoute
  '/reports/aging': typeof AppReportsAgingRoute
  '/reports/customer-profit': typeof AppReportsCustomerProfitRoute
  '/reports/pnl': typeof AppReportsPnlRoute
  '/reports/product-profit': typeof AppReportsProductProfitRoute
  '/reports/purchase-detail': typeof AppReportsPurchaseDetailRoute
  '/reports/revenue': typeof AppReportsRevenueRoute
  '/reports/sales-detail': typeof AppReportsSalesDetailRoute
  '/reports/salesperson': typeof AppReportsSalespersonRoute
  '/settings/opening': typeof AppSettingsOpeningRoute
  '/settings/permissions': typeof AppSettingsPermissionsRoute
  '/settings/users': typeof AppSettingsUsersRoute
  '/settlement/customer': typeof AppSettlementCustomerRoute
  '/settlement/vendor': typeof AppSettlementVendorRoute
  '/statements/customer': typeof AppStatementsCustomerRoute
  '/statements/vendor': typeof AppStatementsVendorRoute
  '/inventory': typeof AppInventoryIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/print/$docType/$id': typeof AppPrintDocTypeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/contacts': typeof AppContactsRoute
  '/_app/expenses': typeof AppExpensesRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/payables': typeof AppPayablesRoute
  '/_app/products': typeof AppProductsRoute
  '/_app/receivables': typeof AppReceivablesRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/docs/inventory-adjust': typeof AppDocsInventoryAdjustRoute
  '/_app/docs/purchase-order': typeof AppDocsPurchaseOrderRoute
  '/_app/docs/purchase-receipt': typeof AppDocsPurchaseReceiptRoute
  '/_app/docs/quotation': typeof AppDocsQuotationRoute
  '/_app/docs/sales-invoice': typeof AppDocsSalesInvoiceRoute
  '/_app/docs/sales-order': typeof AppDocsSalesOrderRoute
  '/_app/docs/sales-return': typeof AppDocsSalesReturnRoute
  '/_app/inventory/ledger': typeof AppInventoryLedgerRoute
  '/_app/reports/aging': typeof AppReportsAgingRoute
  '/_app/reports/customer-profit': typeof AppReportsCustomerProfitRoute
  '/_app/reports/pnl': typeof AppReportsPnlRoute
  '/_app/reports/product-profit': typeof AppReportsProductProfitRoute
  '/_app/reports/purchase-detail': typeof AppReportsPurchaseDetailRoute
  '/_app/reports/revenue': typeof AppReportsRevenueRoute
  '/_app/reports/sales-detail': typeof AppReportsSalesDetailRoute
  '/_app/reports/salesperson': typeof AppReportsSalespersonRoute
  '/_app/settings/opening': typeof AppSettingsOpeningRoute
  '/_app/settings/permissions': typeof AppSettingsPermissionsRoute
  '/_app/settings/users': typeof AppSettingsUsersRoute
  '/_app/settlement/customer': typeof AppSettlementCustomerRoute
  '/_app/settlement/vendor': typeof AppSettlementVendorRoute
  '/_app/statements/customer': typeof AppStatementsCustomerRoute
  '/_app/statements/vendor': typeof AppStatementsVendorRoute
  '/_app/inventory/': typeof AppInventoryIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/print/$docType/$id': typeof AppPrintDocTypeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/contacts'
    | '/expenses'
    | '/notifications'
    | '/payables'
    | '/products'
    | '/receivables'
    | '/settings'
    | '/docs/inventory-adjust'
    | '/docs/purchase-order'
    | '/docs/purchase-receipt'
    | '/docs/quotation'
    | '/docs/sales-invoice'
    | '/docs/sales-order'
    | '/docs/sales-return'
    | '/inventory/ledger'
    | '/reports/aging'
    | '/reports/customer-profit'
    | '/reports/pnl'
    | '/reports/product-profit'
    | '/reports/purchase-detail'
    | '/reports/revenue'
    | '/reports/sales-detail'
    | '/reports/salesperson'
    | '/settings/opening'
    | '/settings/permissions'
    | '/settings/users'
    | '/settlement/customer'
    | '/settlement/vendor'
    | '/statements/customer'
    | '/statements/vendor'
    | '/inventory/'
    | '/settings/'
    | '/print/$docType/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/contacts'
    | '/expenses'
    | '/notifications'
    | '/payables'
    | '/products'
    | '/receivables'
    | '/'
    | '/docs/inventory-adjust'
    | '/docs/purchase-order'
    | '/docs/purchase-receipt'
    | '/docs/quotation'
    | '/docs/sales-invoice'
    | '/docs/sales-order'
    | '/docs/sales-return'
    | '/inventory/ledger'
    | '/reports/aging'
    | '/reports/customer-profit'
    | '/reports/pnl'
    | '/reports/product-profit'
    | '/reports/purchase-detail'
    | '/reports/revenue'
    | '/reports/sales-detail'
    | '/reports/salesperson'
    | '/settings/opening'
    | '/settings/permissions'
    | '/settings/users'
    | '/settlement/customer'
    | '/settlement/vendor'
    | '/statements/customer'
    | '/statements/vendor'
    | '/inventory'
    | '/settings'
    | '/print/$docType/$id'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/contacts'
    | '/_app/expenses'
    | '/_app/notifications'
    | '/_app/payables'
    | '/_app/products'
    | '/_app/receivables'
    | '/_app/settings'
    | '/_app/'
    | '/_app/docs/inventory-adjust'
    | '/_app/docs/purchase-order'
    | '/_app/docs/purchase-receipt'
    | '/_app/docs/quotation'
    | '/_app/docs/sales-invoice'
    | '/_app/docs/sales-order'
    | '/_app/docs/sales-return'
    | '/_app/inventory/ledger'
    | '/_app/reports/aging'
    | '/_app/reports/customer-profit'
    | '/_app/reports/pnl'
    | '/_app/reports/product-profit'
    | '/_app/reports/purchase-detail'
    | '/_app/reports/revenue'
    | '/_app/reports/sales-detail'
    | '/_app/reports/salesperson'
    | '/_app/settings/opening'
    | '/_app/settings/permissions'
    | '/_app/settings/users'
    | '/_app/settlement/customer'
    | '/_app/settlement/vendor'
    | '/_app/statements/customer'
    | '/_app/statements/vendor'
    | '/_app/inventory/'
    | '/_app/settings/'
    | '/_app/print/$docType/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/receivables': {
      id: '/_app/receivables'
      path: '/receivables'
      fullPath: '/receivables'
      preLoaderRoute: typeof AppReceivablesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products': {
      id: '/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payables': {
      id: '/_app/payables'
      path: '/payables'
      fullPath: '/payables'
      preLoaderRoute: typeof AppPayablesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses': {
      id: '/_app/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts': {
      id: '/_app/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AppContactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/inventory/': {
      id: '/_app/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AppInventoryIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/statements/vendor': {
      id: '/_app/statements/vendor'
      path: '/statements/vendor'
      fullPath: '/statements/vendor'
      preLoaderRoute: typeof AppStatementsVendorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/statements/customer': {
      id: '/_app/statements/customer'
      path: '/statements/customer'
      fullPath: '/statements/customer'
      preLoaderRoute: typeof AppStatementsCustomerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settlement/vendor': {
      id: '/_app/settlement/vendor'
      path: '/settlement/vendor'
      fullPath: '/settlement/vendor'
      preLoaderRoute: typeof AppSettlementVendorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settlement/customer': {
      id: '/_app/settlement/customer'
      path: '/settlement/customer'
      fullPath: '/settlement/customer'
      preLoaderRoute: typeof AppSettlementCustomerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/users': {
      id: '/_app/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AppSettingsUsersRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/permissions': {
      id: '/_app/settings/permissions'
      path: '/permissions'
      fullPath: '/settings/permissions'
      preLoaderRoute: typeof AppSettingsPermissionsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/opening': {
      id: '/_app/settings/opening'
      path: '/opening'
      fullPath: '/settings/opening'
      preLoaderRoute: typeof AppSettingsOpeningRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/reports/salesperson': {
      id: '/_app/reports/salesperson'
      path: '/reports/salesperson'
      fullPath: '/reports/salesperson'
      preLoaderRoute: typeof AppReportsSalespersonRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/sales-detail': {
      id: '/_app/reports/sales-detail'
      path: '/reports/sales-detail'
      fullPath: '/reports/sales-detail'
      preLoaderRoute: typeof AppReportsSalesDetailRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/revenue': {
      id: '/_app/reports/revenue'
      path: '/reports/revenue'
      fullPath: '/reports/revenue'
      preLoaderRoute: typeof AppReportsRevenueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/purchase-detail': {
      id: '/_app/reports/purchase-detail'
      path: '/reports/purchase-detail'
      fullPath: '/reports/purchase-detail'
      preLoaderRoute: typeof AppReportsPurchaseDetailRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/product-profit': {
      id: '/_app/reports/product-profit'
      path: '/reports/product-profit'
      fullPath: '/reports/product-profit'
      preLoaderRoute: typeof AppReportsProductProfitRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/pnl': {
      id: '/_app/reports/pnl'
      path: '/reports/pnl'
      fullPath: '/reports/pnl'
      preLoaderRoute: typeof AppReportsPnlRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/customer-profit': {
      id: '/_app/reports/customer-profit'
      path: '/reports/customer-profit'
      fullPath: '/reports/customer-profit'
      preLoaderRoute: typeof AppReportsCustomerProfitRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/aging': {
      id: '/_app/reports/aging'
      path: '/reports/aging'
      fullPath: '/reports/aging'
      preLoaderRoute: typeof AppReportsAgingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/ledger': {
      id: '/_app/inventory/ledger'
      path: '/inventory/ledger'
      fullPath: '/inventory/ledger'
      preLoaderRoute: typeof AppInventoryLedgerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/docs/sales-return': {
      id: '/_app/docs/sales-return'
      path: '/docs/sales-return'
      fullPath: '/docs/sales-return'
      preLoaderRoute: typeof AppDocsSalesReturnRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/docs/sales-order': {
      id: '/_app/docs/sales-order'
      path: '/docs/sales-order'
      fullPath: '/docs/sales-order'
      preLoaderRoute: typeof AppDocsSalesOrderRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/docs/sales-invoice': {
      id: '/_app/docs/sales-invoice'
      path: '/docs/sales-invoice'
      fullPath: '/docs/sales-invoice'
      preLoaderRoute: typeof AppDocsSalesInvoiceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/docs/quotation': {
      id: '/_app/docs/quotation'
      path: '/docs/quotation'
      fullPath: '/docs/quotation'
      preLoaderRoute: typeof AppDocsQuotationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/docs/purchase-receipt': {
      id: '/_app/docs/purchase-receipt'
      path: '/docs/purchase-receipt'
      fullPath: '/docs/purchase-receipt'
      preLoaderRoute: typeof AppDocsPurchaseReceiptRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/docs/purchase-order': {
      id: '/_app/docs/purchase-order'
      path: '/docs/purchase-order'
      fullPath: '/docs/purchase-order'
      preLoaderRoute: typeof AppDocsPurchaseOrderRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/docs/inventory-adjust': {
      id: '/_app/docs/inventory-adjust'
      path: '/docs/inventory-adjust'
      fullPath: '/docs/inventory-adjust'
      preLoaderRoute: typeof AppDocsInventoryAdjustRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/print/$docType/$id': {
      id: '/_app/print/$docType/$id'
      path: '/print/$docType/$id'
      fullPath: '/print/$docType/$id'
      preLoaderRoute: typeof AppPrintDocTypeIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppSettingsRouteChildren {
  AppSettingsOpeningRoute: typeof AppSettingsOpeningRoute
  AppSettingsPermissionsRoute: typeof AppSettingsPermissionsRoute
  AppSettingsUsersRoute: typeof AppSettingsUsersRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsOpeningRoute: AppSettingsOpeningRoute,
  AppSettingsPermissionsRoute: AppSettingsPermissionsRoute,
  AppSettingsUsersRoute: AppSettingsUsersRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppContactsRoute: typeof AppContactsRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPayablesRoute: typeof AppPayablesRoute
  AppProductsRoute: typeof AppProductsRoute
  AppReceivablesRoute: typeof AppReceivablesRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppDocsInventoryAdjustRoute: typeof AppDocsInventoryAdjustRoute
  AppDocsPurchaseOrderRoute: typeof AppDocsPurchaseOrderRoute
  AppDocsPurchaseReceiptRoute: typeof AppDocsPurchaseReceiptRoute
  AppDocsQuotationRoute: typeof AppDocsQuotationRoute
  AppDocsSalesInvoiceRoute: typeof AppDocsSalesInvoiceRoute
  AppDocsSalesOrderRoute: typeof AppDocsSalesOrderRoute
  AppDocsSalesReturnRoute: typeof AppDocsSalesReturnRoute
  AppInventoryLedgerRoute: typeof AppInventoryLedgerRoute
  AppReportsAgingRoute: typeof AppReportsAgingRoute
  AppReportsCustomerProfitRoute: typeof AppReportsCustomerProfitRoute
  AppReportsPnlRoute: typeof AppReportsPnlRoute
  AppReportsProductProfitRoute: typeof AppReportsProductProfitRoute
  AppReportsPurchaseDetailRoute: typeof AppReportsPurchaseDetailRoute
  AppReportsRevenueRoute: typeof AppReportsRevenueRoute
  AppReportsSalesDetailRoute: typeof AppReportsSalesDetailRoute
  AppReportsSalespersonRoute: typeof AppReportsSalespersonRoute
  AppSettlementCustomerRoute: typeof AppSettlementCustomerRoute
  AppSettlementVendorRoute: typeof AppSettlementVendorRoute
  AppStatementsCustomerRoute: typeof AppStatementsCustomerRoute
  AppStatementsVendorRoute: typeof AppStatementsVendorRoute
  AppInventoryIndexRoute: typeof AppInventoryIndexRoute
  AppPrintDocTypeIdRoute: typeof AppPrintDocTypeIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppContactsRoute: AppContactsRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPayablesRoute: AppPayablesRoute,
  AppProductsRoute: AppProductsRoute,
  AppReceivablesRoute: AppReceivablesRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppDocsInventoryAdjustRoute: AppDocsInventoryAdjustRoute,
  AppDocsPurchaseOrderRoute: AppDocsPurchaseOrderRoute,
  AppDocsPurchaseReceiptRoute: AppDocsPurchaseReceiptRoute,
  AppDocsQuotationRoute: AppDocsQuotationRoute,
  AppDocsSalesInvoiceRoute: AppDocsSalesInvoiceRoute,
  AppDocsSalesOrderRoute: AppDocsSalesOrderRoute,
  AppDocsSalesReturnRoute: AppDocsSalesReturnRoute,
  AppInventoryLedgerRoute: AppInventoryLedgerRoute,
  AppReportsAgingRoute: AppReportsAgingRoute,
  AppReportsCustomerProfitRoute: AppReportsCustomerProfitRoute,
  AppReportsPnlRoute: AppReportsPnlRoute,
  AppReportsProductProfitRoute: AppReportsProductProfitRoute,
  AppReportsPurchaseDetailRoute: AppReportsPurchaseDetailRoute,
  AppReportsRevenueRoute: AppReportsRevenueRoute,
  AppReportsSalesDetailRoute: AppReportsSalesDetailRoute,
  AppReportsSalespersonRoute: AppReportsSalespersonRoute,
  AppSettlementCustomerRoute: AppSettlementCustomerRoute,
  AppSettlementVendorRoute: AppSettlementVendorRoute,
  AppStatementsCustomerRoute: AppStatementsCustomerRoute,
  AppStatementsVendorRoute: AppStatementsVendorRoute,
  AppInventoryIndexRoute: AppInventoryIndexRoute,
  AppPrintDocTypeIdRoute: AppPrintDocTypeIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
